name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello everyone in the World!"
      - name: Print Goodbye
        run: echo "Done - Bye!"
